### ISSUE TITLE
Fix the mod.

### ISSUE THREAD

**Issue by Butterfinger191-gif** [Ruombus/Deep-Seadustry#1]

**Comment by Butterfinger191-gif** [comment]
![Screenshot_20231128_125400_Mindustry.jpg](https://github.com/Ruombus/Deep-Seadustry/assets/62821554/900fbe77-9afd-4b15-948f-6f4c2af3a90c)

**Comment by Butterfinger191-gif** [comment]
Filtration unit json is the issue

**Comment by Ruombus** [comment]
Hello
I know this is 2 weeks late, but i was kinda foucused on other groups of things.
Thank you for pointing out this issue, and im sorry it took so long to fix
